server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/georgezeng/work/git/private/test-cloud/test-config
          default-label: ${configBranch:development}
