management.security.enabled: false
spring:
  rabbitmq:
    port: 5672
  sleuth.sampler.percentage: 1
  zipkin.sender.type: rabbit
  session.store-type: redis
  
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000